spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: planning
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://seremak.ovh/realms/simple-bills
          jwk-set-uri: https://seremak.ovh/realms/simple-bills/protocol/openid-connect/certs

server:
  port: 8082

custom-properties:
  allowed-origin: "http://localhost:8080"
  expense-categories:
    - food
    - travel
    - education
    - fun
    - utility
    - health
    - insurance
    - car
    - public transport
    - sport
    - electronics
    - garden
  income-categories:
    - salary

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui