services:

  simple-bills:
    build: simple-bills-gui
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - transaction-management
      - planning
      - asset-management

  transaction-management:
    build: transaction-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - common_env.env

  planning:
    build: planning
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - common_env.env

  asset-management:
    build: asset-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - common_env.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
