services:

  transaction-management:
    build: transaction-management
    ports:
      - 8080:8080
    restart: always

  planning:
    build: planning
    ports:
      - 8080:8080
    restart: always

  asset-management:
    build: asset-management
    ports:
      - 8080:8080
    restart: always

  simple-bills-gui:
      build: simple-bills-gui
      ports: 
          - 80:80
          - 443:443

  mongodb:
    image: mongo:4.4.16
    ports:
      - 27027:27027
    volumes:
      - data:/mongodb

volumes:
  data:
