services:

  transaction-management:
    build: transaction-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  planning:
    build: planning
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  asset-management:
    build: asset-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  simple-bills-gui:
    build: simple-bills-gui
    ports:
      - 80:80
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.16
    ports:
      - 27027:27027
    volumes:
      - mongo_data:/mongodb

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 443:8080
    depends_on:
      - postgres
    command: start-dev --db-url-host postgres --db-url-database keycloak --db-username keycloak --hostname https://keycloak-lukaszse.cloud.okteto.net --db-password Passw0rd --hostname-strict false --hostname-strict-https false --http-enabled true

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Passw0rd

volumes:
  mongo_data:
  postgres_data:
    driver: local
