services:

  simple-bills-gui:
    build: 
      context: simple-bills-gui
      dockerfile: DockerfileLocal
    ports:
      - 80:80
    depends_on:
      - transaction-management
      - planning
      - asset-management

  transaction-management:
    build: transaction-management
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - keycloak
    ports:
      - 8081:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  planning:
    build: planning
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - keycloak
    ports:
      - 8082:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  asset-management:
    build: asset-management
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - keycloak
    ports:
      - 8083:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  mongodb:
    image: mongo:4.4.16
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - 8085:8080
    command: start-dev --db-url-host postgres --db-url-database keycloak --db-username keycloak

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Passw0rd

volumes:
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  postgres_data:
    driver: local
  