services:

  transaction-management:
    build: transaction-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - MONGO_URI=${MONGODB_URI}

  planning:
    build: planning
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - MONGO_URI=${MONGODB_URI}

  asset-management:
    build: asset-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - MONGO_URI=${MONGODB_URI}

  simple-bills-gui:
    build: simple-bills-gui
    ports:
      - 80:80
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
