services:

  transaction-management:
    build: transaction-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq

  planning:
    build: planning
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq

  asset-management:
    build: asset-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq

  simple-bills-gui:
    build: simple-bills-gui
    ports:
      - 80:80
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.16
    command: ["--tsl"]
    ports:
      - 27027:27027
    volumes:
      - mongo_data:/mongodb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
