services:

  transaction-management:
    build: transaction-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  planning:
    build: planning
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  asset-management:
    build: asset-management
    ports:
      - 443:8080
    restart: unless-stopped
    depends_on:
      - mongodb

  simple-bills-gui:
    build: simple-bills-gui
    ports:
      - 80:80
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.16
    ports:
      - 27027:27027
    volumes:
      - mongo_data:/mongodb

volumes:
  mongo_data:
  postgres_data:
    driver: local
