spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: transaction
      uri: mongodb://mongodb:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-lukaszse.cloud.okteto.net/realms/simple-bills
          jwk-set-uri: https://keycloak-lukaszse.cloud.okteto.net/realms/simple-bills/protocol/openid-connect/certs
  rabbitmq:
    host: 37.233.102.95

simple-bills-gui: "https://simple-bills-gui-lukaszse.cloud.okteto.net"