spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: transaction
      uri: mongodb://localhost:27027
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/simple-bills
          jwk-set-uri: http://localhost:8085/realms/simple-bills/protocol/openid-connect/certs

server:
  port: 8080

simple-bills-gui: "http://localhost:8089"