spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: asset
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ubuntudev.llseremak.p5.tiktalik.io/realms/simple-bills
          jwk-set-uri: https://ubuntudev.llseremak.p5.tiktalik.io/realms/simple-bills/protocol/openid-connect/certs

server:
  port: 8083

custom-properties:
  allowed-origin: "http://localhost:8080"
  transaction-url: "http://localhost:8081"
  planning-url: "http://localhost:8082"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui