spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: asset
      uri: mongodb://mongodb:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ubuntudev.llseremak.p5.tiktalik.io/realms/simple-bills
          jwk-set-uri: http://ubuntudev.llseremak.p5.tiktalik.io/realms/simple-bills/protocol/openid-connect/certs
  rabbitmq:
    host: 37.233.102.95
    
server:
  port: 8080

custom-properties:
  simple-bills-gui: "https://simple-bills-gui-lukaszse.cloud.okteto.net"
  transaction-url: "https://transaction-management-lukaszse.cloud.okteto.net/"
  planning-url: "https://planning-lukaszse.cloud.okteto.net/"