spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: asset
      uri: mongodb+srv://simple:bills@cluster0.i30j4gd.mongodb.net/?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://37.233.102.95:8443/realms/simple-bills
          jwk-set-uri: https://37.233.102.95:8443/realms/simple-bills/protocol/openid-connect/certs
  rabbitmq:
    host: https://37.233.102.95
    
server:
  port: 8080

custom-properties:
  simple-bills-gui: "https://simple-bills-lukaszse.cloud.okteto.net/"
  transaction-url: "https://transaction-management-lukaszse.cloud.okteto.net/"
  planning-url: "https://planning-lukaszse.cloud.okteto.net/"