spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: asset
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/simple-bills
          jwk-set-uri: http://localhost:8085/realms/simple-bills/protocol/openid-connect/certs

server:
  port: 8083

custom-properties:
  simple-bills-gui: "http://localhost"
  transaction-url: "http://localhost:8081"
  planning-url: "http://localhost:8082"