@startuml
'https://plantuml.com/deployment-diagram


node "Serwer VPS (Linux)" <<device>> as linux {
    artifact "docker-compose.yml" <<artifact>> as dcompKeycloak
    component "Keycloak \nOAuth2.0/OpenID Connect" <<component>> as keycloak
}

node "Komputer PC" <<device>> as pc {
    component "Przeglądarka Internetowa" <<component>>
}

node "Platforma Okteto (Kubernetes) \nlukaszse namespace" <<executionEnvironment>> as okteto {

    artifact "docker-compose.yml" <<artifact>> as dComp

    node "simple-bills" <<pod>> as gui {
    component "Aplikacja kliencka Simple Bills" <<component>>
    }

    node "asset-management" <<pod>> as asset {
    component "Mikrousługa Asset Management" <<component>>
    }

    node "transaction-management" <<pod>> as transaction {
    component "Mikrousługa Transaction Management" <<component>>
    }

    node "planning" <<pod>> as planning {
    component "Mikrousługa Planning" <<component>>
    }

    node "rabbitmq" <<pod>> as rabbit {
    component "Broker RabbitMQ" <<component>>
    }
}


database mongo [
<b>MongoDB SaaS
===

Baza danych Transaction
----
Baza danych Asset
----
Baza danych Planning
]

dComp ..> gui
dComp ... planning
dComp ...> asset
dComp ..> transaction
dComp ...> rabbit
dcompKeycloak ..> keycloak
pc -left- okteto : HTTPS
linux -- okteto : HTTPS
pc -- linux : HTTPS
okteto ---- mongo : HTTPS


@enduml